name: Renovate

on:
  schedule:
    # Run once a week on Monday at 3 AM UTC
    - cron: '0 3 * * MON'
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Self-hosted Renovate
        uses: renovatebot/renovate-action@v40
        with:
          token: ${{ secrets.RENOVATE_TOKEN || secrets.GITHUB_TOKEN }}
